"use client";

import { ChangeEvent, lazy, Suspense, useState } from "react";
import type { LearnscapeBlueprint } from "@/lib/blueprint/schema";
import { pendulumBlueprint, sampleBlueprints } from "@/lib/blueprint/fixtures";
import { calculateTitration } from "@/lib/titration/engine";
import { calculateCircuit } from "@/lib/circuit/engine";
import { statistics } from "@/lib/statistics/simulations";
import { approximatePeriod } from "@/lib/pendulum/engine";
import { choosePendulumExperiment, inferPendulumBeliefs, pendulumBeliefLabels, type AdaptiveExperiment, type PendulumBeliefs } from "@/lib/learner/pendulum";

const PendulumWorld = lazy(() => import("./PendulumWorld"));

type View = "home" | "upload" | "blueprint" | "world" | "library";
type WorldTab = "lab" | "molecular" | "curve" | "equation";

const sampleText = "A 25.0 mL sample of 0.100 M sodium hydroxide is titrated with 0.100 M hydrochloric acid. At the equivalence point, acid and base react in a 1:1 ratio.";
const statusLabel = (status: LearnscapeBlueprint["validationStatus"]) => status === "template_validated" ? "Validated template" : status === "experimental_preview" ? "Experimental preview" : "Unsupported concept";

export default function Home() {
  const [view, setView] = useState<View>("home");
  const [blueprint, setBlueprint] = useState<LearnscapeBlueprint>(pendulumBlueprint);
  const [provider, setProvider] = useState<"llama" | "gpt">("llama");
  const [sourceText, setSourceText] = useState(sampleText);
  const [fileName, setFileName] = useState("");
  const [analyzing, setAnalyzing] = useState(false);
  const [notice, setNotice] = useState("");
  const [worldTab, setWorldTab] = useState<WorldTab>("lab");
  const [addedMl, setAddedMl] = useState(0);
  const [voltage, setVoltage] = useState(6);
  const [resistance, setResistance] = useState(6);
  const [closed, setClosed] = useState(true);
  const [outlier, setOutlier] = useState(13);
  const [missionStep, setMissionStep] = useState(1);
  const [prediction, setPrediction] = useState("");
  const [confidence, setConfidence] = useState(80);
  const [resultReviewed, setResultReviewed] = useState("");
  const [explanation, setExplanation] = useState("");
  const [transferChoice, setTransferChoice] = useState("");
  const [missionComplete, setMissionComplete] = useState(false);
  const [pendulumLength, setPendulumLength] = useState(1.4);
  const [pendulumMass, setPendulumMass] = useState(1);
  const [pendulumAngle, setPendulumAngle] = useState(40);
  const [pendulumDamping, setPendulumDamping] = useState(.03);
  const [pendulumReleased, setPendulumReleased] = useState(false);
  const [preparedExperiment, setPreparedExperiment] = useState<AdaptiveExperiment | null>(null);

  const titration = calculateTitration(addedMl);
  const circuit = calculateCircuit(voltage, resistance, closed);
  const values = [4, 5, 6, 6, 7, 8, outlier];
  const stats = statistics(values);
  const worldKind = blueprint.recommendedExperience.templateId;
  const pendulumBeliefs = inferPendulumBeliefs({ prediction, confidence, experimentCompleted: pendulumReleased, reflection: resultReviewed, explanation, transferChoice });
  const adaptiveExperiment = choosePendulumExperiment(pendulumBeliefs);
  const activeExperiment = preparedExperiment ?? adaptiveExperiment;
  const hasExperimented = worldKind === "pendulum_world" ? pendulumReleased : worldKind === "acid_base_titration" ? addedMl > 0 : worldKind === "ohms_law_circuit" ? voltage !== 6 || resistance !== 6 || !closed : outlier !== 13;
  const pendulumOutcome = activeExperiment.id === "compare_mass" ? `The 1 kg baseline and ${pendulumMass.toFixed(1)} kg test bob have the same ${approximatePeriod(pendulumLength).toFixed(2)} s ideal period. Mass changes energy, not swing time.` : activeExperiment.id === "compare_length" ? `Stretching the cord to ${pendulumLength.toFixed(1)} m increases the ideal period to ${approximatePeriod(pendulumLength).toFixed(2)} s. Length changes swing time.` : `Potential energy peaks at release; kinetic energy peaks at the bottom. The total only falls when damping removes energy.`;
  const outcome = worldKind === "pendulum_world" ? pendulumOutcome : worldKind === "acid_base_titration" ? `At ${addedMl.toFixed(2)} mL added, the pH is ${titration.pH.toFixed(2)} and ${titration.excess === "none" ? "neither strong reactant is in excess" : `${titration.excess} remains in excess`}.` : worldKind === "ohms_law_circuit" ? `The circuit now carries ${circuit.current.toFixed(2)} A at ${voltage} V and ${resistance} Ω.` : `Moving the outlier to ${outlier} changed the mean to ${stats.mean.toFixed(2)}, while the median is ${stats.median.toFixed(2)}.`;
  const achievement = worldKind === "pendulum_world" && pendulumReleased && pendulumLength >= 2 ? "Period Cartographer" : worldKind === "acid_base_titration" && Math.abs(addedMl - titration.equivalenceMl) <= .1 ? "Equivalence Hunter" : worldKind === "ohms_law_circuit" && Math.abs(circuit.current - 1.5) < .02 ? "Current Architect" : worldKind === "statistics_explorer" && outlier >= 18 ? "Robustness Detective" : "";
  const insightScore = (prediction ? 20 : 0) + (hasExperimented ? 25 : 0) + (resultReviewed ? 20 : 0) + (explanation.trim().length >= 20 ? 20 : 0) + (transferChoice ? 15 : 0);

  const resetMission = () => { setMissionStep(1); setPrediction(""); setConfidence(80); setResultReviewed(""); setExplanation(""); setTransferChoice(""); setMissionComplete(false); setPendulumReleased(false); setPreparedExperiment(null); };
  const choose = (next: LearnscapeBlueprint) => { setBlueprint(next); setView("blueprint"); setWorldTab("lab"); setNotice(""); resetMission(); };
  const openWorld = (_trigger?: unknown) => { void _trigger; setView("world"); setAddedMl(0); setVoltage(6); setResistance(6); setClosed(true); setOutlier(13); setPendulumLength(1.4); setPendulumMass(1); setPendulumAngle(40); setPendulumDamping(.03); setPendulumReleased(false); resetMission(); };
  const startGuidedDemo = () => { setBlueprint(pendulumBlueprint); openWorld(); };
  const prepareAdaptiveExperiment = () => {
    if (adaptiveExperiment.id === "compare_mass") { setPendulumLength(1.4); setPendulumMass(3); setPendulumAngle(40); setPendulumDamping(.03); }
    if (adaptiveExperiment.id === "compare_length") { setPendulumLength(2.2); setPendulumMass(1); setPendulumAngle(40); setPendulumDamping(.03); }
    if (adaptiveExperiment.id === "trace_energy") { setPendulumLength(1.4); setPendulumMass(1); setPendulumAngle(60); setPendulumDamping(0); }
    setPendulumReleased(false); setPreparedExperiment(adaptiveExperiment);
  };
  const analyze = async () => {
    setAnalyzing(true); setNotice("");
    try {
      const response = await fetch("/api/analyze", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ text: sourceText, provider }) });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error ?? "Analysis did not complete.");
      setBlueprint(data.blueprint); setNotice(data.warning ? `Analysis note: ${data.warning}` : `Analyzed with ${data.provider === "llama" ? "your local Llama server" : data.provider}.`); setView("blueprint");
    } catch (error) { setNotice(error instanceof Error ? error.message : "Analysis did not complete."); }
    finally { setAnalyzing(false); }
  };
  const onFile = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setFileName(file.name); setNotice("Image selected. Confirm the extracted text below before analysis; GPT vision can be enabled later."); };
  const onPendulumExperiment = () => { setPendulumReleased(true); if (missionStep === 2) setMissionStep(3); };
  const mission = worldKind !== "unsupported" ? <Mission kind={worldKind} missionStep={missionStep} setMissionStep={setMissionStep} prediction={prediction} setPrediction={setPrediction} confidence={confidence} setConfidence={setConfidence} hasExperimented={hasExperimented} outcome={outcome} resultReviewed={resultReviewed} setResultReviewed={setResultReviewed} explanation={explanation} setExplanation={setExplanation} transferChoice={transferChoice} setTransferChoice={setTransferChoice} missionComplete={missionComplete} setMissionComplete={setMissionComplete} score={insightScore} achievement={achievement} onReset={resetMission} adaptation={worldKind === "pendulum_world" ? { beliefs: pendulumBeliefs, experiment: activeExperiment, onPrepare: prepareAdaptiveExperiment } : null} /> : null;

  return <main className="app-shell">
    <header className="topbar">
      <button className="brand" onClick={() => setView("home")} aria-label="Go to Learnscape home"><span className="brand-mark">L</span><span>learnscape</span></button>
      <div className="top-meta">
        <span className="presence"><i />Demo-ready</span>
        <button className="text-button" onClick={() => setView("library")}>Library</button><button className="avatar" aria-label="Profile">M</button>
      </div>
    </header>

    {view === "home" && <section className="home-view">
      <div className="eyebrow">PREDICTIVE LEARNING WORLDS <span>•</span> FOR STEM</div>
      <div className="hero-grid"><div className="hero-copy"><p className="kicker">THE WORLD IS THE LESSON</p><h1>Predict what happens.<br/><em>Discover why.</em></h1><p className="hero-description">Turn course material into spatial experiments where students reveal how they think—and leave with evidence.</p><div className="hero-actions"><button className="primary-button" onClick={startGuidedDemo}>Enter the observatory <span>↗</span></button><button className="secondary-button demo-button" onClick={() => setView("upload")}><i>+</i> Build from a source</button></div><div className="learning-loop"><span>Predict</span><b>→</b><span>Intervene</span><b>→</b><span>Observe</span><b>→</b><span>Revise</span><b>→</b><span>Transfer</span></div></div>
        <div className="hero-stage pendulum-hero" aria-label="A pendulum predictive world preview"><div className="stage-label">FLAGSHIP WORLD <b>01 / PENDULUM</b></div><div className="hero-mission-card"><span>STUDENT HYPOTHESIS</span><b>A heavier bob will complete the swing faster.</b><small>useful next experiment found</small></div><div className="hero-pendulum"><div className="hero-cord"/><div className="hero-bob"/></div><div className="hero-ghost"><div/><i/></div><div className="hero-orbit"/><div className="stage-readout"><span>learning signal</span><strong>68%</strong><small>mass misconception · ready to test</small></div><div className="energy-mini"><span><i/></span><span><i/></span><small>PE ↔ KE</small></div></div></div>

      <section className="value-strip"><article><span>01</span><div><b>Source-grounded</b><p>Every world traces back to the uploaded page—not a generic course.</p></div></article><article><span>02</span><div><b>Prediction-locked</b><p>Learners commit before controls unlock, making their thinking visible.</p></div></article><article><span>03</span><div><b>Transfer-checked</b><p>Progress means applying the relationship in a changed situation.</p></div></article></section>

      <section className="pilot-section"><div className="section-heading"><div><p className="kicker">CURATED CONCEPT MISSIONS</p><h2>From intuition to evidence.</h2></div><button className="text-button" onClick={() => setView("library")}>Open mission library →</button></div><div className="pilot-grid">{sampleBlueprints.map((item, index) => <button className={`pilot-card pilot-${index}`} onClick={() => choose(item)} key={item.id}><span className="card-index">WORLD 0{index + 1}</span><span className={`badge ${item.validationStatus}`}>{statusLabel(item.validationStatus)}</span><div className="card-art"><i/><b/><em/></div><div className="mission-reward"><span>{index === 0 ? "adapts to your thinking" : "evidence-backed"}</span><span>100 insight</span></div><h3>{item.title}</h3><p>{item.recommendedExperience.templateId === "pendulum_world" ? "Make a prediction, reveal a misconception, and receive the experiment you need next." : item.recommendedExperience.templateId === "acid_base_titration" ? "Find the invisible boundary where excess changes sides." : item.recommendedExperience.templateId === "ohms_law_circuit" ? "Design two different circuits that produce the same current." : "Move one value and discover which center resists the change."}</p><span className="card-link">Enter world <b>→</b></span></button>)}</div></section>
    </section>}

    {view === "upload" && <section className="workflow-view"><div className="workflow-rail"><p className="kicker">NEW LEARNSCAPE</p><h2>Bring in the page.</h2><p>Learnscape traces the source, identifies a causal relationship, and proposes the most honest interactive medium.</p><ol><li className="active">1 <span>Source</span></li><li>2 <span>Blueprint</span></li><li>3 <span>Mission</span></li></ol></div><div className="upload-panel"><div className="panel-top"><span className="eyebrow">SOURCE INGESTION</span><button className="text-button" onClick={() => setView("home")}>Cancel</button></div><div className="drop-zone"><input id="source-image" type="file" accept="image/*" onChange={onFile}/><label htmlFor="source-image"><span className="upload-icon">↑</span><strong>{fileName || "Drop a textbook page here"}</strong><small>or choose an image from your computer</small></label></div><div className="or-line"><span>OR START WITH A DEMO-SAFE SOURCE</span></div><div className="sample-pills">{sampleBlueprints.map(item => <button key={item.id} onClick={() => { setBlueprint(item); setSourceText(item.source.summary); }}>{item.title}</button>)}</div><label className="field-label">PASTE OR CONFIRM EXTRACTED TEXT<textarea value={sourceText} onChange={event => setSourceText(event.target.value)} placeholder="Paste a textbook excerpt…" /></label><div className="provider-row"><div><strong>Analysis provider</strong><small>Local Llama works without API credits. GPT‑5.6 remains optional.</small></div><div className="provider-toggle"><button className={provider === "llama" ? "selected" : ""} onClick={() => setProvider("llama")}>Local Llama</button><button className={provider === "gpt" ? "selected" : ""} onClick={() => setProvider("gpt")}>GPT‑5.6</button></div></div>{notice && <p className="notice">{notice}</p>}<button className="primary-button wide" disabled={analyzing} onClick={analyze}>{analyzing ? "Analyzing source…" : "Analyze & propose a mission"}<span>→</span></button></div></section>}

    {view === "blueprint" && <section className="blueprint-view"><aside className="workflow-rail blueprint-rail"><button className="back" onClick={() => setView("upload")}>← Source</button><p className="kicker">LEARNING BLUEPRINT</p><h2>{blueprint.title}</h2><span className={`badge ${blueprint.validationStatus}`}>{statusLabel(blueprint.validationStatus)}</span><p>{blueprint.source.summary}</p><div className="source-snippet">“{blueprint.source.relevantExcerpts[0]?.text}”</div></aside><div className="blueprint-main"><div className="panel-top"><div><span className="eyebrow">MISSION BLUEPRINT READY</span><h2>A world with a learning contract.</h2></div><button className="text-button" onClick={() => setView("library")}>Save to library</button></div><div className="blueprint-tiles"><article><span>01</span><h3>What the learner must notice</h3><ul>{blueprint.concepts.map(c => <li key={c.id}><b>{c.name}</b><small>{c.explanation}</small></li>)}</ul></article><article><span>02</span><h3>Equation connection</h3>{blueprint.equations.map(eq => <div className="equation" key={eq.id}>{eq.latex}<small>{eq.plainLanguage}</small></div>)}</article><article><span>03</span><h3>Mission contract</h3><div className="recommendation"><i>◎</i><b>Predict → evidence → transfer</b><p>The learner cannot earn mastery by clicking through. They must commit, test, explain, and apply.</p></div></article></div><div className="integrity-callout"><b>Scientific & educational integrity</b><span>{blueprint.assumptions[0]}</span><span>{blueprint.limitations[0]}</span></div><div className="blueprint-actions"><button className="secondary-button" onClick={() => setView("upload")}>Adjust interpretation</button><button className="primary-button" onClick={() => openWorld(false)}>{worldKind === "unsupported" ? "Explore the blueprint" : "Launch mission"} <span>→</span></button></div></div></section>}

    {view === "library" && <section className="library-view"><div className="section-heading"><div><p className="kicker">WORLD LIBRARY</p><h1>A studio for causal intuition.</h1><p className="library-intro">Each stamp represents a relationship you predicted, tested, and transferred—not a lesson you merely opened.</p></div><button className="primary-button" onClick={() => setView("upload")}>New source <span>+</span></button></div><div className="passport-summary"><div className="passport-seal">L</div><div><small>CONCEPT PASSPORT</small><b>0 / 4 worlds mastered</b></div><div className="passport-stat"><strong>0</strong><span>evidence stamps</span></div><div className="passport-stat"><strong>0</strong><span>transfer wins</span></div></div><div className="library-grid">{sampleBlueprints.map((item, index) => <button className="library-card" key={item.id} onClick={() => choose(item)}><div className={`library-visual lv-${index}`}><span>{item.recommendedExperience.templateId === "pendulum_world" ? "θ ↔ E" : item.recommendedExperience.templateId === "acid_base_titration" ? "pH" : item.recommendedExperience.templateId === "ohms_law_circuit" ? "I = V/R" : "x̄"}</span><i>{index === 0 ? "FLAGSHIP" : "UNEXPLORED"}</i></div><div><span className={`badge ${item.validationStatus}`}>{statusLabel(item.validationStatus)}</span><h2>{item.title}</h2><p>{item.domain} · 3-step mission · 100 insight</p></div><b>→</b></button>)}</div></section>}

    {view === "world" && <section className={`world-view ${worldKind === "pendulum_world" ? "pendulum-experience" : ""}`}>
      <div className="world-top"><button className="back" onClick={() => setView("library")}>← Library</button><div><span className="eyebrow">{statusLabel(blueprint.validationStatus)}</span><h2>{blueprint.title}</h2></div><div className="world-hud"><div><small>YOUR STEP</small><b>{missionComplete ? "complete" : missionStep === 1 ? "predict" : missionStep < 4 ? "test" : "explain"}</b></div></div><button className="reset-button" onClick={openWorld}>↺ Reset</button></div>
      {achievement && <div className="discovery-toast"><i>✦</i><div><small>DISCOVERY UNLOCKED</small><b>{achievement}</b></div><span>Evidence, not speed, earned this.</span></div>}
      {mission}
      {worldKind === "pendulum_world" ? <Suspense fallback={<div className="world-canvas world-loading"><span>Preparing the observatory…</span></div>}><PendulumWorld length={pendulumLength} mass={pendulumMass} angle={pendulumAngle} damping={pendulumDamping} setLength={setPendulumLength} setMass={setPendulumMass} setAngle={setPendulumAngle} setDamping={setPendulumDamping} locked={!prediction} focused={Boolean(preparedExperiment)} focus={activeExperiment.id} onExperiment={onPendulumExperiment} /></Suspense> : worldKind === "acid_base_titration" ? <TitrationWorld state={titration} addedMl={addedMl} setAddedMl={setAddedMl} tab={worldTab} setTab={setWorldTab} locked={!prediction} /> : worldKind === "ohms_law_circuit" ? <CircuitWorld voltage={voltage} resistance={resistance} closed={closed} setVoltage={setVoltage} setResistance={setResistance} setClosed={setClosed} locked={!prediction} /> : worldKind === "statistics_explorer" ? <StatisticsWorld values={values} outlier={outlier} setOutlier={setOutlier} mean={stats.mean} median={stats.median} locked={!prediction} /> : <UnsupportedWorld blueprint={blueprint} />}
    </section>}
  </main>;
}

function LockOverlay() { return <div className="control-lock"><span>◎</span><b>Lock a prediction to activate controls</b><small>Your first guess becomes part of the evidence trail.</small></div>; }

function TitrationWorld({ state, addedMl, setAddedMl, tab, setTab, locked }: { state: ReturnType<typeof calculateTitration>; addedMl: number; setAddedMl: (n: number) => void; tab: WorldTab; setTab: (t: WorldTab) => void; locked: boolean }) {
  const points = Array.from({ length: 16 }, (_, i) => calculateTitration(i * 3).pH);
  return <div className="world-layout"><section className="world-canvas titration-canvas"><div className="view-tabs">{(["lab", "molecular", "curve", "equation"] as WorldTab[]).map(item => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</div>{tab === "lab" && <div className="lab-scene"><div className="lab-burette"><div style={{ height: `${Math.max(8, 76 - addedMl)}%` }}/><i/></div><div className="lab-probe"/><div className={`lab-beaker ${state.excess}`}><div className="liquid"/><span className="ions ion-a">H₃O⁺</span><span className="ions ion-b">OH⁻</span><span className="ions ion-c">H₂O</span></div><div className="live-chip">pH <strong>{state.pH.toFixed(2)}</strong></div></div>}{tab === "molecular" && <div className="molecular-scene"><p>Representative particles — not a literal particle count.</p><div className="molecule-field">{Array.from({length: state.excess === "none" ? 6 : 16}, (_,i) => <i className={state.excess === "hydroxide" ? "oh" : state.excess === "hydronium" ? "h3o" : "water"} key={i}>{state.excess === "hydroxide" ? "OH⁻" : state.excess === "hydronium" ? "H₃O⁺" : "H₂O"}</i>)}</div></div>}{tab === "curve" && <div className="curve-scene"><p>Live titration curve</p><div className="chart-grid">{points.map((point, i) => <i key={i} style={{ left: `${i * 6.1 + 3}%`, bottom: `${point * 5.4 + 5}%` }}/>)}</div><div className="axis-label">titrant added →</div></div>}{tab === "equation" && <div className="equation-scene"><span>1:1 neutralization</span><strong>n = M × V</strong><p>{(state.baseM * state.initialBaseMl / 1000).toFixed(4)} mol base initially</p><div>{state.excess === "none" ? "At equivalence: pH ≈ 7" : `Excess ${state.excess} controls the pH.`}</div></div>}</section><aside className={`control-panel ${locked ? "is-locked" : ""}`}>{locked && <LockOverlay/>}<p className="kicker">EXPERIMENT CONTROLS</p><h3>Add titrant</h3><div className="button-row"><button disabled={locked} onClick={() => setAddedMl(Math.min(50, addedMl + .05))}>+ one drop</button><button disabled={locked} onClick={() => setAddedMl(Math.min(50, addedMl + .5))}>+ 0.5 mL</button><button disabled={locked} onClick={() => setAddedMl(Math.min(50, addedMl + 1))}>+ 1 mL</button><button disabled={locked} className="jump-button" onClick={() => setAddedMl(24.95)}>Jump near equivalence</button></div><input disabled={locked} aria-label="Titrant volume" type="range" min="0" max="50" step="0.05" value={addedMl} onChange={e => setAddedMl(Number(e.target.value))}/><div className="metric-grid"><div><small>ADDED</small><b>{addedMl.toFixed(2)} mL</b></div><div><small>EQUIVALENCE</small><b>{state.equivalenceMl.toFixed(2)} mL</b></div><div><small>STATE</small><b>{state.excess === "none" ? "balanced" : `excess ${state.excess}`}</b></div><div><small>TOTAL VOLUME</small><b>{state.totalMl.toFixed(2)} mL</b></div></div><p className="model-note">Simplified strong acid–strong base model at 25 °C.</p></aside></div>;
}

function CircuitWorld({ voltage, resistance, closed, setVoltage, setResistance, setClosed, locked }: { voltage: number; resistance: number; closed: boolean; setVoltage: (v: number) => void; setResistance: (r: number) => void; setClosed: (v: boolean) => void; locked: boolean }) { const state = calculateCircuit(voltage, resistance, closed); return <div className="world-layout"><section className="world-canvas circuit-canvas"><div className={`circuit-drawing ${closed ? "on" : "off"}`}><div className="battery">+ <b>{voltage}V</b> −</div><div className="wire top-wire"/><div className="wire bottom-wire"/><button disabled={locked} className={`switch ${closed ? "closed" : ""}`} onClick={() => setClosed(!closed)} aria-label="Toggle circuit switch"><i/></button><div className="resistor">R<br/><b>{resistance}Ω</b></div><div className="bulb"><i style={{ opacity: 0.15 + state.brightness / 120 }}/><span>brightness {state.brightness}%</span></div>{closed && Array.from({length: 8}, (_,i) => <span className="charge" style={{ animationDelay: `${i * -.35}s` }} key={i}>+</span>)}</div><div className="circuit-equation">I = V / R <strong>{state.current.toFixed(2)} A</strong></div></section><aside className={`control-panel ${locked ? "is-locked" : ""}`}>{locked && <LockOverlay/>}<p className="kicker">EXPERIMENT CONTROLS</p><h3>Change the circuit</h3><label>Voltage <b>{voltage} V</b><input disabled={locked} aria-label="Voltage" type="range" min="0" max="12" value={voltage} onChange={e => setVoltage(Number(e.target.value))}/></label><label>Resistance <b>{resistance} Ω</b><input disabled={locked} aria-label="Resistance" type="range" min="1" max="12" value={resistance} onChange={e => setResistance(Number(e.target.value))}/></label><button disabled={locked} className="switch-button" onClick={() => setClosed(!closed)}>{closed ? "Open switch" : "Close switch"}</button><button disabled={locked} className="target-button" onClick={() => { setVoltage(9); setResistance(6); setClosed(true); }}>Try target: 1.50 A</button><div className="metric-grid"><div><small>CURRENT</small><b>{state.current.toFixed(2)} A</b></div><div><small>POWER</small><b>{state.power.toFixed(2)} W</b></div><div><small>FLOW</small><b>{closed ? "closed loop" : "open loop"}</b></div><div><small>MODEL</small><b>conceptual</b></div></div><p className="model-note">Animated charges represent conventional current, not electron drift speed.</p></aside></div>; }

function StatisticsWorld({ values, outlier, setOutlier, mean, median, locked }: { values: number[]; outlier: number; setOutlier: (n:number) => void; mean: number; median: number; locked: boolean }) { return <div className="world-layout"><section className="world-canvas stats-canvas"><p className="eyebrow">EXPERIMENTAL PREVIEW</p><h2>Which center moves more?</h2><div className="dot-plot">{values.map((value, index) => <span key={index} className={index === values.length - 1 ? "outlier-dot" : ""} style={{ left: `${(value / 20) * 88 + 5}%` }}><i/>{value}</span>)}</div><div className="center-lines"><b style={{ left: `${mean / 20 * 88 + 5}%` }}>mean {mean.toFixed(1)}</b><b style={{ left: `${median / 20 * 88 + 5}%` }}>median {median.toFixed(1)}</b></div><p>Move the outlier, then compare how mean and median respond.</p></section><aside className={`control-panel ${locked ? "is-locked" : ""}`}>{locked && <LockOverlay/>}<p className="kicker">EXPERIMENT CONTROLS</p><h3>Move the outlier</h3><input disabled={locked} aria-label="Outlier value" type="range" min="1" max="20" value={outlier} onChange={e => setOutlier(Number(e.target.value))}/><button disabled={locked} className="target-button" onClick={() => setOutlier(20)}>Push it to the edge</button><div className="metric-grid"><div><small>OUTLIER</small><b>{outlier}</b></div><div><small>MEAN</small><b>{mean.toFixed(2)}</b></div><div><small>MEDIAN</small><b>{median.toFixed(2)}</b></div><div><small>STATUS</small><b>experimental</b></div></div><p className="model-note">Template-based learning preview. This is not a general statistics engine.</p></aside></div>; }

function UnsupportedWorld({ blueprint }: { blueprint: LearnscapeBlueprint }) { return <div className="unsupported-world"><span className="eyebrow">INTENTIONAL UNSUPPORTED STATE</span><h1>Learnscape understood the source.</h1><p>A validated interactive template for this concept is not available yet. Here is the structured blueprint it would use next.</p><div className="coming-grid"><article><b>Source concepts</b>{blueprint.concepts.map(c => <span key={c.id}>{c.name}</span>)}</article><article><b>Learning objective</b><span>{blueprint.learningObjectives[0]}</span></article><article><b>Coming next</b><span>{blueprint.recommendedExperience.rationale}</span></article></div></div>; }

type MissionAdaptation = { beliefs: PendulumBeliefs; experiment: AdaptiveExperiment; onPrepare: () => void } | null;

function Mission({ kind, missionStep, setMissionStep, prediction, setPrediction, confidence, setConfidence, hasExperimented, outcome, resultReviewed, setResultReviewed, explanation, setExplanation, transferChoice, setTransferChoice, missionComplete, setMissionComplete, score, achievement, onReset, adaptation }: { kind: string; missionStep: number; setMissionStep: (n:number) => void; prediction: string; setPrediction: (v:string) => void; confidence: number; setConfidence: (n:number) => void; hasExperimented: boolean; outcome: string; resultReviewed: string; setResultReviewed: (v:string) => void; explanation: string; setExplanation: (t:string) => void; transferChoice: string; setTransferChoice: (v:string) => void; missionComplete: boolean; setMissionComplete: (v:boolean) => void; score:number; achievement:string; onReset:()=>void; adaptation: MissionAdaptation }) {
  const content = kind === "pendulum_world" ? { question: "If the bob becomes three times heavier, what happens to the ideal period?", predictions: ["The swing becomes faster", "The period stays nearly the same", "The swing becomes slower"], transfer: "To make the ideal pendulum take longer to complete a swing, you should…", answers: ["increase its mass", "shorten the cord", "lengthen the cord"], correct: "lengthen the cord" } : kind === "acid_base_titration" ? { question: "What will happen as acid approaches the equivalence volume?", predictions: ["The pH will fall at a steady rate", "The pH change will suddenly become much larger", "The pH will stay basic after equivalence"], transfer: "If the base concentration doubles but its volume stays the same, the equivalence volume should…", answers: ["halve", "stay the same", "double"], correct: "double" } : kind === "ohms_law_circuit" ? { question: "If voltage doubles while resistance stays fixed, what happens to current?", predictions: ["Current halves", "Current stays the same", "Current doubles"], transfer: "If both voltage and resistance double, current should…", answers: ["halve", "stay the same", "double"], correct: "stay the same" } : { question: "Which measure will move more when the outlier moves farther away?", predictions: ["The median", "The mean", "Both equally"], transfer: "For a highly skewed salary dataset, the more robust center is usually the…", answers: ["mean", "median", "range"], correct: "median" };
  const stages = ["Predict", "Test", "Explain"];
  const visibleStep = missionStep === 1 ? 1 : missionStep < 4 ? 2 : 3;
  const notebook = [prediction && `Prediction locked at ${confidence}% confidence`, hasExperimented && "A parameter was changed", resultReviewed && "Observed evidence was compared", explanation.trim().length >= 20 && "A causal explanation was recorded", transferChoice && "Transfer answer submitted"].filter(Boolean) as string[];
  const lockPrediction = () => { adaptation?.onPrepare(); setMissionStep(2); };
  const reflect = (value: string) => { setResultReviewed(value); setMissionStep(4); };
  if (missionComplete) return <section className="mission completion-shell"><div className="concept-passport"><div className="passport-mark">✓</div><div><p className="kicker">CONCEPT COMPLETE</p><h2>You found the rule.</h2><p>You predicted, tested, and applied the idea in a new situation.</p><div className="stamp-row"><span>+{score} insight</span>{achievement && <span>✦ {achievement}</span>}</div></div><button className="secondary-button" onClick={onReset}>Try again</button></div></section>;
  return <section className="mission mission-v2"><div className="mission-card">
    <nav className="mission-steps" aria-label="Mission progress">{stages.map((stage,i) => <span className={`${i + 1 === visibleStep ? "active" : ""} ${i + 1 < visibleStep ? "done" : ""}`} key={stage}><i>{i + 1 < visibleStep ? "✓" : i + 1}</i>{stage}</span>)}</nav>
    {missionStep === 1 && <><p className="kicker">MAKE A PREDICTION</p><h2>{content.question}</h2><p className="mission-help">Commit to what you think. The world will respond to your idea.</p><div className="prediction-grid">{content.predictions.map(option => <button className={prediction === option ? "selected" : ""} onClick={() => setPrediction(option)} key={option}>{option}</button>)}</div><div className="confidence-choice"><span>How sure are you?</span>{[{value:50,label:"Not sure"},{value:80,label:"Pretty sure"},{value:100,label:"Certain"}].map(item => <button className={confidence === item.value ? "selected" : ""} onClick={() => setConfidence(item.value)} key={item.value}>{item.label}</button>)}</div><button className="primary-button" disabled={!prediction} onClick={lockPrediction}>Test my prediction <span>→</span></button></>}
    {missionStep === 2 && <><p className="kicker">RUN ONE TEST</p><h2>{adaptation?.experiment.title ?? "Change one thing."}</h2><p className="mission-help">{adaptation?.experiment.prompt ?? "Change one variable and observe the result."}</p>{adaptation && <div className="adaptive-experiment prepared"><div><small>READY FOR YOU</small><b>{adaptation.experiment.setup}</b></div><span>setup ready ✓</span></div>}<div className={`evidence-status ${hasExperimented ? "ready" : ""}`}><i>{hasExperimented ? "✓" : "○"}</i><div><b>{hasExperimented ? "Result ready" : "Release the pendulum in the world"}</b><span>{hasExperimented ? outcome : "Everything is set. Run the test once and watch what changes."}</span></div></div><button className="primary-button" disabled={!hasExperimented} onClick={() => setMissionStep(3)}>See what it means <span>→</span></button></>}
    {missionStep === 3 && <><p className="kicker">COMPARE</p><h2>Did the evidence change your mind?</h2><div className="compare-grid"><article><small>YOUR PREDICTION · {confidence}%</small><b>{prediction}</b></article><article><small>RESULT</small><b>{outcome}</b></article></div><div className="model-revision"><button onClick={() => reflect("held")}>My prediction held up</button><button onClick={() => reflect("revised")}>I changed my mind</button></div></>}
    {missionStep === 4 && <><p className="kicker">EXPLAIN & TRANSFER</p><h2>Turn the observation into a rule.</h2><textarea value={explanation} onChange={e => setExplanation(e.target.value)} placeholder="Explain why the outcome happened. Name the variables and the causal relationship…"/><div className="explanation-meter"><span style={{width:`${Math.min(100, explanation.trim().length * 3)}%`}}/><small>{explanation.trim().length < 20 ? "Add a causal explanation" : "Explanation has enough evidence to continue"}</small></div><div className="transfer-card"><b>{content.transfer}</b><div>{content.answers.map(answer => <button className={transferChoice === answer ? "selected" : ""} onClick={() => setTransferChoice(answer)} key={answer}>{answer}</button>)}</div>{transferChoice && transferChoice !== content.correct && <small className="transfer-feedback">That conflicts with the relationship you just observed. Try another explanation.</small>}</div><button className="primary-button" disabled={explanation.trim().length < 20 || transferChoice !== content.correct} onClick={() => setMissionComplete(true)}>Stamp concept passport <span>✦</span></button></>}
    <details className="mission-details"><summary>Learning evidence <span>for instructors</span></summary><div className="evidence-trail">{notebook.length ? notebook.map((item,i) => <p key={item}><i>{i+1}</i>{item}</p>) : <p>No evidence yet.</p>}</div>{adaptation && <div className="instructor-lens"><p>Current estimate based on the learner’s choices.</p>{(Object.entries(adaptation.beliefs) as [keyof PendulumBeliefs, number][]).sort((a,b) => b[1] - a[1]).map(([id,probability]) => <div className="belief-row" key={id}><span>{pendulumBeliefLabels[id]}</span><div><i style={{width:`${Math.round(probability * 100)}%`}}/></div><b>{Math.round(probability * 100)}%</b></div>)}<small>Next test: {adaptation.experiment.title}</small></div>}</details>
  </div></section>;
}
