"""Train and export the tiny transition model used by the pendulum demo."""

from pathlib import Path
import json
import numpy as np
from sklearn.neural_network import MLPRegressor

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "lib" / "pendulum" / "model-weights.ts"
RNG = np.random.default_rng(42)
COUNT = 40_000
DT = 0.04

theta = RNG.uniform(-1.35, 1.35, COUNT)
omega = RNG.uniform(-4.5, 4.5, COUNT)
length = RNG.uniform(0.65, 2.35, COUNT)
gravity = RNG.uniform(4.0, 12.0, COUNT)
damping = RNG.uniform(0.0, 0.13, COUNT)

def accel(t, o):
    return -(gravity / length) * np.sin(t) - damping * o

a1 = accel(theta, omega)
t2, o2 = theta + omega * DT / 2, omega + a1 * DT / 2
a2 = accel(t2, o2)
t3, o3 = theta + o2 * DT / 2, omega + a2 * DT / 2
a3 = accel(t3, o3)
t4, o4 = theta + o3 * DT, omega + a3 * DT
a4 = accel(t4, o4)
next_theta = theta + DT * (omega + 2 * o2 + 2 * o3 + o4) / 6
next_omega = omega + DT * (a1 + 2 * a2 + 2 * a3 + a4) / 6

x = np.column_stack([
    np.sin(theta), np.cos(theta), omega / 5,
    (length - 1.5) / .85, (gravity - 8) / 4, (damping - .065) / .065,
])
y = np.column_stack([(next_theta - theta) / .22, (next_omega - omega) / 1.6])

model = MLPRegressor(
    hidden_layer_sizes=(24, 24), activation="tanh", solver="adam",
    random_state=42, max_iter=220, early_stopping=True,
    validation_fraction=.12, n_iter_no_change=18, batch_size=256,
    learning_rate_init=.002,
)
model.fit(x, y)

payload = {
    "dt": DT,
    "coefs": [matrix.tolist() for matrix in model.coefs_],
    "intercepts": [vector.tolist() for vector in model.intercepts_],
    "validationScore": float(model.best_validation_score_),
    "iterations": int(model.n_iter_),
}
OUTPUT.write_text(
    "// Generated by scripts/train_pendulum_model.py\n"
    "export const pendulumModelWeights = " + json.dumps(payload, separators=(",", ":")) + " as const;\n"
)
print(f"wrote {OUTPUT} · validation R² {model.best_validation_score_:.5f}")
