import type { LearnscapeBlueprint } from "./schema";

const base = (id: string, title: string, domain: LearnscapeBlueprint["domain"], templateId: LearnscapeBlueprint["recommendedExperience"]["templateId"], representation: LearnscapeBlueprint["recommendedExperience"]["representation"], validationStatus: LearnscapeBlueprint["validationStatus"], concepts: LearnscapeBlueprint["concepts"], variables: LearnscapeBlueprint["variables"], equations: LearnscapeBlueprint["equations"]): LearnscapeBlueprint => ({
  id, title, domain, source: { sourceType: "sample", summary: "A deterministic Learnscape sample page used for the guided demo.", relevantExcerpts: concepts.map(c => ({ text: c.explanation, conceptIds: [c.id] })) }, concepts, variables, equations,
  relationships: variables.slice(0, 2).map((v, i) => ({ cause: v.id, effect: variables[(i + 1) % variables.length]?.id ?? v.id, relationship: "depends_on" as const, explanation: "The values change together in this simplified conceptual model." })),
  learningObjectives: concepts.map(c => `Explain how ${c.name.toLowerCase()} changes the system.`), commonMisconceptions: ["A diagram is not the system itself; it is a representation for reasoning."], recommendedExperience: { templateId, representation, rationale: "This representation makes the key causal relationship visible and manipulable." }, assumptions: ["This is a simplified conceptual model designed to make the relationship visible."], limitations: ["Not a laboratory-grade or fully general simulation."], validationStatus,
});

export const titrationBlueprint = base("sample-titration", "Acid–Base Titration", "chemistry", "acid_base_titration", "3d_lab", "template_validated", [
  { id: "neutralization", name: "Neutralization", explanation: "Hydronium and hydroxide react in a 1:1 relationship.", importance: "primary" },
  { id: "equivalence", name: "Equivalence point", explanation: "At equivalence, neither strong reactant remains in excess.", importance: "primary" },
], [{ id: "acid", name: "Hydrochloric acid added", symbol: "Vₐ", unit: "mL", description: "Titrant volume from the burette.", manipulable: true }, { id: "base", name: "Sodium hydroxide", symbol: "Vᵦ", unit: "mL", description: "Starting analyte volume.", manipulable: false }], [{ id: "moles", latex: "n = M × V", plainLanguage: "Moles equal molarity multiplied by volume.", variableIds: ["acid", "base"] }, { id: "ph", latex: "pH = −log₁₀[H₃O⁺]", plainLanguage: "pH reflects excess hydronium concentration.", variableIds: ["acid"] }]);

export const circuitBlueprint = base("sample-circuit", "Ohm’s Law Circuit Lab", "physics", "ohms_law_circuit", "interactive_circuit", "template_validated", [{ id: "current", name: "Current", explanation: "Current depends on voltage and resistance in a closed circuit.", importance: "primary" }, { id: "resistance", name: "Resistance", explanation: "Resistance opposes current.", importance: "primary" }], [{ id: "voltage", name: "Voltage", symbol: "V", unit: "V", description: "Potential difference supplied by the source.", manipulable: true }, { id: "resistance", name: "Resistance", symbol: "R", unit: "Ω", description: "Opposition to current.", manipulable: true }], [{ id: "ohm", latex: "I = V / R", plainLanguage: "Current equals voltage divided by resistance.", variableIds: ["voltage", "resistance"] }]);

export const statisticsBlueprint = base("sample-statistics", "Outliers & Center", "statistics", "statistics_explorer", "2d_simulation", "experimental_preview", [{ id: "mean", name: "Mean", explanation: "The mean balances every data value.", importance: "primary" }, { id: "median", name: "Median", explanation: "The median is the middle ordered value.", importance: "primary" }], [{ id: "outlier", name: "Outlier", unit: "value", description: "A point far from the rest of the data.", manipulable: true }], [{ id: "mean", latex: "x̄ = Σx / n", plainLanguage: "Mean is the total divided by the count.", variableIds: ["outlier"] }]);

export const sampleBlueprints = [titrationBlueprint, circuitBlueprint, statisticsBlueprint];
